apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2022-01-20T02:37:30Z"
    generation: 1
    labels:
      app: blog-django-py
      app.kubernetes.io/component: blog-django-py
      app.kubernetes.io/instance: blog-django-py
    name: blog-django-py
    namespace: fiap-aso-g20
  spec:
    lookupPolicy:
      local: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
